# Class 13: Maps

Plan for today:
- Visualizing data with heatmaps
- Creating maps

In [ ]:
import YData

# YData.download.download_class_code(14)   # get class code    
# YData.download.download_class_code(14, True)  # get the code with the answers 
# YData.download_homework(6)  # get homework 6

YData.download_data("dennys.csv")

YData.download.download_data("States_shapefile.geojson")
YData.download.download_data("state_demographics.csv")
YData.download.download_data("ne_110m_graticules_10.prj")
YData.download.download_data("ne_110m_graticules_10.shp")
YData.download.download_data("ne_110m_graticules_10.shx")
YData.download.download_data("ne_110m_graticules_10.dbf")

YData.download_data('daily_bike_totals.csv')

If you are using colabs, you should install the YData packages by uncommenting and running the code below and run the code below to mount the your google drive.

In [31]:
## If you are using Google Colabs, you should install the YData packages and mount the your google drive by uncommenting and running the code below.

# !pip install https://github.com/emeyers/YData_package/tarball/master
# from google.colab import drive
# drive.mount('/content/drive')

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px

import matplotlib.pyplot as plt
%matplotlib inline

## Pivot tables and heatmaps

Heatmaps allow us to view data that is a function of two variables. 

In order to create a heatmap, we first need first transformat out data into a DataFrame that has appropirate rows and columns. One way we can do this is to use the pandas `.pivot_table(index = , columns = , values = , aggfunc = )` method, where the arguments to this method are:

- `index`: The variable we want in the rows of out DataFrame
- `columns`: The variable we want in the columns of our DataFrame
- `values`: The values we want to be in the DataFrame
- `aggfunc`: The function we will use to aggregate our data 

Let's apply the `.pivot_table()` method to our gapmider data to create a DataFrame called `gapminder_continent_wide` where:

- The rows are the different continents
- The columns are the year
- The values in the DataFrame are the average life expectancy (For each continent in each year)

In [4]:
# Generate a pivot table from the gapminder data

gapminder = px.data.gapminder()   # the plotly package comes with the gapminder data

gapminder.head()

Now that we have the appropriate DataFrame, let's use the seaborn's `heatmap()` function to visualize it!

In [35]:
# We can create heatmaps in seaborn to visualize the pivot table

## Spatial mapping with geopandas

Visualizing spatial data through maps is another powerful way to see trends in data. There are several mapping packages in Python. Here we will use the geopandas package to create maps. 

The geopandas package defines a geopandas DataFrame, which is the same as a pandas DataFrame but has an additional column called `geometry` which specifies geographic information. 

Let's explore this now!

### Visualizing boundaries

Let's start by looking some geopanda DataFrames and visualizing some geometric boundaries.

Below we load the gapminder data again and get the gapminder data from 2007. We also show which maps come with geopandas.

In [36]:
import geopandas as gpd

Let's get a geopandas DataFrame that has the countries in the world...

In [37]:
# View the world geopandas DataFrame

url = "https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_countries.zip"
world = gpd.read_file(url)


# print the data type
print(type(world))

# look at the first few rows of the data
world.head()

<class 'geopandas.geodataframe.GeoDataFrame'>

,featurecla,scalerank,LABELRANK,SOVEREIGNT,SOV_A3,ADM0_DIF,LEVEL,TYPE,TLC,ADMIN,...,FCLASS_TR,FCLASS_ID,FCLASS_PL,FCLASS_GR,FCLASS_IT,FCLASS_NL,FCLASS_SE,FCLASS_BD,FCLASS_UA,geometry
0,Admin-0 country,1,6,Fiji,FJI,0,2,Sovereign country,1,Fiji,...,None,None,None,None,None,None,None,None,None,"MULTIPOLYGON (((180 -16.06713, 180 -16.55522, ..."
1,Admin-0 country,1,3,United Republic of Tanzania,TZA,0,2,Sovereign country,1,United Republic of Tanzania,...,None,None,None,None,None,None,None,None,None,"POLYGON ((33.90371 -0.95, 34.07262 -1.05982, 3..."
2,Admin-0 country,1,7,Western Sahara,SAH,0,2,Indeterminate,1,Western Sahara,...,Unrecognized,Unrecognized,Unrecognized,None,None,Unrecognized,None,None,None,"POLYGON ((-8.66559 27.65643, -8.66512 27.58948..."
3,Admin-0 country,1,2,Canada,CAN,0,2,Sovereign country,1,Canada,...,None,None,None,None,None,None,None,None,None,"MULTIPOLYGON (((-122.84 49, -122.97421 49.0025..."
4,Admin-0 country,1,2,United States of America,US1,1,2,Country,1,United States of America,...,None,None,None,None,None,None,None,None,None,"MULTIPOLYGON (((-122.84 49, -120 49, -117.0312..."

In [38]:
# Plot a world map with particular properties

In [39]:
# Plot just the United States

### Coordinate reference systems and projections

A coordinate reference system (CRS) is a framework used to precisely measure locations on the surface of the Earth as coordinates. The goal of any spatial reference system is to create a common reference frame in which locations can be measured precisely and consistently as coordinates, which can then be shared unambiguously, so that any recipient can identify the same location that was originally intended by the originator.

There are two different types of coordinate reference systems: Geographic Coordinate Systems and Projected Coordinate Systems. [Projected coordinate systems](https://en.wikipedia.org/wiki/List_of_map_projections) map 3D coordinates into a 2D plane so they can be plotted. Different projected coordiate systems perserve different properties, such as keeping all angles intact which is usefor for navigation (e.g., the Mercator projection) or keeping the size of land areas intact (e.g., the Eckert IV projection). 

A detailed discussion of CRS is beyond the scope of the class. But for the purposes of this class, it is just important that all layers in a map are using the same project (otherwise, for example, data points representing cities and the underlying spatial map won't line up). 

Let's very briefly explore different map projections...

In [40]:
# Read Graticules (lines on a map)
graticules = gpd.read_file("ne_110m_graticules_10.shp")
print(graticules.crs)
graticules.head(3)

EPSG:4326

,degrees,direction,display,dd,ScaleRank,geometry
0,80,N,80 N,80.0,6,"LINESTRING (180 79.99848, 179.99664 79.99848, ..."
1,70,N,70 N,70.0,6,"LINESTRING (180 69.99847, 179.99664 69.99847, ..."
2,60,N,60 N,60.0,6,"LINESTRING (180 59.99866, 179.99664 59.99866, ..."

In [41]:
# Web Mercator projection - perserves angles (EPSG:4326 projection)

# print the default CRS



# plot the map

In [42]:
# Eckert IV is an equal-area projection  ("ESRI:54012")

In [43]:
# Robinson projection - neither equal-area nor conformal ("ESRI:54030")

To learn more about "What your favorite map projection says about you" see: https://xkcd.com/977/

### Maps with layers and markers

We can also plot points on a map. When doing so, it's important that the points and the underlying map use the same coordinate reference system (CRS).

Let's add Denny's locations to the map of the United States!

In [44]:
# Let's start by getting a map of just the United States

In [45]:
# visualize just the United States

In [46]:
# Get the coordinate reference system (CRS) for our map

Let's now load our Denny's data!

In [47]:
# Let's load our Denny's data
dennys = pd.read_csv("dennys.csv")
dennys.head(3)

   Unnamed: 0           address       city state    zip  longitude  latitude
0           1       2900 Denali  Anchorage    AK  99503  -149.8767   61.1953
1           2  3850 Debarr Road  Anchorage    AK  99508  -149.8090   61.2097
2           3  1929 Airport Way  Fairbanks    AK  99701  -147.7600   64.8366

To convert longitude and latitude coordinates into geometric objects; i.e., we will convert them into Shaply objects.  We can use the `gpd.points_from_xy(long, lat)` function.

In [48]:
# Let's convert our longitude and latitude coordinates into geometric (Shapely) objects

In [49]:
# Let's now convert out data into a geopandas DataFrame

In [50]:
# We can plot the location of the Denny's using the plot function

In [51]:
# Let's check the CRS

Before plotting data, we should set the appropriate coordinate reference system (CRS). This is partlcularly imporant when we are combining different layers on a map, such as putting city locations on the map that has the outlines of regional borders. 

The CRS that uses longitude and latitude coordinates is the [World Geodetic System 1984 (WGS84)](https://epsg.io/4326). This system is often referred to by its EPSG Geodetic Parameter Dataset code which is `4326`. 

Thus, we should set the set coordinate system to be EPSG 4326. We can do this using the method `.set_crs(4326)`. Let's set this on our `dennys_gpd` DataFrame.

In [52]:
# Let's set the CRS to match the CRS of our map (which is EPSG 4326)

Now that we have our Denny's location in the same coordinate system as our map, we can add the points to the map.

In [53]:
#state_map = gpd.read_file("States_shapefile.geojson")

### Choropleth maps

In choropleth maps, predefined regions are filled in with colors based values of interest. 

Typically to create a choropleth map we join data of interest onto a map. 

Let's explrore this now...

In [54]:
import plotly.express as px

gapminder_2007 = px.data.gapminder().query("year == 2007")   # the plotly package comes with the gapminder data


# Join the gapminder data onto our world map

In [55]:
# Plot a choropleth map of life expectancy

In [56]:
# Change the color scale

In [57]:
# We can plot quantiles

### Another choropleth map example

Let's fit a choropleth map examining which states in the USA are growing in terms of people having lots of childern. 

Any thoughts on which state this might be? 

To start, let's load a map with the outlines of the states in the USA, and load demographic data.

In [58]:
state_map = gpd.read_file("States_shapefile.geojson")

print(state_map.crs)

state_map.head(3)

EPSG:4326

,FID,Program,State_Code,State_Name,Flowing_St,FID_1,geometry
0,1,PERMIT TRACKING,AL,ALABAMA,F,919,"POLYGON ((-85.07007 31.9807, -85.11515 31.9074..."
1,2,,AK,ALASKA,N,920,"MULTIPOLYGON (((-161.33379 58.73325, -161.3824..."
2,3,AZURITE,AZ,ARIZONA,F,921,"POLYGON ((-114.52063 33.02771, -114.55909 33.0..."

In [59]:
# load demographic data on the states

state_demographics = pd.read_csv("state_demographics.csv")
state_demographics.head(3)

     State     under_5      over_64  bachelors_degree    total
0  Alabama  295811.997   741954.681       1095959.202  4849377
1   Alaska   54518.168    69252.808        202601.300   736732
2  Arizona  430814.976  1070305.956       1810769.196  6731484

In [60]:
# In order to join the DataFrames, we need to make sure the states have the same capitalization

state_demographics2 = state_demographics.copy()
state_demographics2["State"] = state_demographics["State"].apply(str.upper)

state_demographics2.head()

In [61]:
# Join the demographic information on to the the USA map

In [62]:
# Let's plot the map

Is there anything [wrong with this map](https://xkcd.com/1138/)?

In [63]:
# Let's look at the proportion of people under the age of 5

In [64]:
# Let's plot the new map

In [66]:
# Loop over items in a list
a_list = ["first", "second", "third", "forth"]

In [67]:
# Loop over numbers using the range() function

In [68]:
# Can you print the squares of the numbers from 1 to 6?

We can use a loop to build up values in a list...

In [69]:
# Create a list that has the squares of the numbers 1 to 6
# hint: the .append() method will be useful

### Challenge question 1

Can you use loops to sum the numbers 1 to 10? 

Or, to use mathematical notation, can you compute $\sum_{i=1}^{10} i$ ?

In [70]:
# Sum numbers from 1 to 10

### Enumerate

We can use enumerate(my_list) to get both values from a list and sequential index numbers.

In [71]:
# We can use enumerate(my_list) to get both values from a list 
# and sequential index numbers

a_list = ["first", "second", "third", "forth"]

### zip function

We can use `zip(list_1, list_2)` to get values from two lists in a for loop.

In [72]:
list_1 = ["a", "b", "c"]
list_2 = ["x", "y", "z"]

### Challenge question 2

The code below extracts two lists that have the the high and low temperatures from 2014 in NYC. 

Please use for loops to create a list that has the temperature range (high - low temperature) for each day (without using numpy).

In [73]:
import pandas as pd
import matplotlib.pyplot as plt

bikes = pd.read_csv("daily_bike_totals.csv", parse_dates = [0])
bikes_2014 = bikes.query("date > '2013-12-31'").query("date < '2015-01-01'")

max_temps = bikes_2014["max_temperature"].to_list()
min_temps = bikes_2014["min_temperature"].to_list()

print(max_temps[0:5])
print(min_temps[0:5])

[33.08, 33.08, 18.14, 29.12, 39.92]
[24.26, 18.14, 9.14, 8.24, 27.14]

In [74]:
# Create a list called "temp_range" that has the temperature range for each day in 2014. Try to do this with and without using the zip() function.

In [75]:
# Alternative solution using the zip function

In [76]:
# Can you do the same calculation using numpy arrays?  
# Which is easier? 
import numpy as np