# Class 15: For loops and writing functions

In this notebook we will continuing learning some of the fundamentals of Python, namely using for loops, conditional statements and writing functions. This material will be useful for analyzing data, and more generally for any programming you do in the future.

In [80]:
import YData

# YData.download.download_class_code(15)       
# YData.download.download_class_code(15, TRUE) # get the code with the answers 
# YData.download.download_homework(6)  # download the homework 

YData.download.download_data("ne_110m_admin_0_countries.zip")
YData.download.download_data("States_shapefile.geojson")
YData.download.download_data("state_demographics.csv")
YData.download_data('daily_bike_totals.csv')
YData.download_image("powers.jpg")

The file `States_shapefile.geojson` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.
The file `state_demographics.csv` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.
The file `daily_bike_totals.csv` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.
The file `powers.jpg` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.

In [81]:
## If you are using Google Colabs, you should install the YData packages and mount the your google drive by uncommenting and running the code below.

# !pip install https://github.com/yuejiechi/YData_package/tarball/master
# from google.colab import drive
# drive.mount('/content/drive')

In [82]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import geopandas as gpd
import plotly.express as px

## 1. Choropleth maps

In choropleth maps, predefined regions are filled in with colors based values of interest. 

Let's fit a choropleth map examining which states in the USA are growing in terms of people having lots of childern. 

Any thoughts on which state this might be? 

To start, let's load a map with the outlines of the states in the USA, and load demographic data.

In [87]:
state_map = gpd.read_file("States_shapefile.geojson")

print(state_map.crs)

state_map.head(3)

EPSG:4326

,FID,Program,State_Code,State_Name,Flowing_St,FID_1,geometry
0,1,PERMIT TRACKING,AL,ALABAMA,F,919,"POLYGON ((-85.07007 31.9807, -85.11515 31.9074..."
1,2,,AK,ALASKA,N,920,"MULTIPOLYGON (((-161.33379 58.73325, -161.3824..."
2,3,AZURITE,AZ,ARIZONA,F,921,"POLYGON ((-114.52063 33.02771, -114.55909 33.0..."

In [88]:
# load demographic data on the states

state_demographics = pd.read_csv("state_demographics.csv")
state_demographics.head(3)

     State     under_5      over_64  bachelors_degree    total
0  Alabama  295811.997   741954.681       1095959.202  4849377
1   Alaska   54518.168    69252.808        202601.300   736732
2  Arizona  430814.976  1070305.956       1810769.196  6731484

In [89]:
# In order to join the DataFrames, we need to make sure the states have the same capitalization

In [90]:
# Join the demographic information on to the the USA map

In [91]:
# Let's plot the map

Is there anything [wrong with this map](https://xkcd.com/1138/)?

In [92]:
# Let's look at the proportion of people under the age of 5

In [93]:
# Let's plot the new map

## 2. Loops

Loops allow us to repeat a process many times. They are particularly useful in conjuction with lists to process and store multiple values.

In [95]:
# Loop over items in a list
a_list = ["first", "second", "third", "forth"]

In [96]:
# Loop over numbers using the range() function

In [97]:
# Can you print the squares of the numbers from 1 to 6?

We can use a loop to build up values in a list...

In [98]:
# Create a list that has the squares of the numbers 1 to 6
# hint: the .append() method will be useful

my_squares = []

### Exercise 1

Can you use loops to sum the numbers 1 to 10? 

Or, to use mathematical notation, can you compute $\sum_{i=1}^{10} i$ ?

In [99]:
# Sum numbers from 1 to 10
my_sum = 0

### Enumerate

We can use enumerate(my_list) to get both values from a list and sequential index numbers.

In [100]:
# We can use enumerate(my_list) to get both values from a list 
# and sequential index numbers

a_list = ["first", "second", "third", "forth"]

### zip function

We can use `zip(list_1, list_2)` to get values from two lists in a for loop.

In [101]:
list_1 = ["a", "b", "c"]
list_2 = ["x", "y", "z"]

### Exercise 2

The code below extracts two lists that have the the high and low temperatures from 2014 in NYC. 

Please use for loops to create a list called `temp_range` that has the temperature range (high - low temperature) for each day.

There are a few ways to do this, so see if you can come up with a solution that works. Try to do this without using numpy, and once you have a solution, see if you can get the same result using numpy.

In [102]:
import pandas as pd
import matplotlib.pyplot as plt

bikes = pd.read_csv("daily_bike_totals.csv", parse_dates = [0])
bikes_2014 = bikes.query("date > '2013-12-31'").query("date < '2015-01-01'")

max_temps = bikes_2014["max_temperature"].to_list()
min_temps = bikes_2014["min_temperature"].to_list()

print(max_temps[0:5])
print(min_temps[0:5])

[33.08, 33.08, 18.14, 29.12, 39.92]
[24.26, 18.14, 9.14, 8.24, 27.14]

In [103]:
# Create a list called "temp_range" that has the temperature range for each day in 2014...

# Start with an empty list
temp_range = [];

In [104]:
# Another solution using for loops (i.e., can you do it with and without using the zip() function)

# Start with an empty list
temp_range2 = [];

In [105]:
# Can you do the same calculation using numpy arrays?  
# Which is easier? 
import numpy as np

## 3a. Review of comparisons

Let's do a very quick review of mathematical and string comparisons in Python.

In [106]:
# Basic math comparison

In [107]:
# Checking the type of a basic math comparison

In [108]:
# We use == to compare whether two items are equal (not 3 = 3)

In [109]:
# We can use the `and` keyword to combine multiple logical statements

In [110]:
# We can also use the `or` keyword to combine multiple logical statements

In [111]:
# We can also compare strings

In [112]:
# Stings compare alphabetically

In [113]:
# Shorter words occur earlier than longer words that have matching letters

## 3b. Conditional Statements 

Conditional statements allow use to excecute particular pieces of code when certain conditions are met; i.e., they execute a piece of code when a Boolean value is True. 

Let's explore!

In [114]:
num_semesters = 7

In [115]:
# Let's look at a conditional statement in a loop