# Class 12: Review practice problems

Here are a few review practice problems based on the problems everyone posted to Canvas

In [9]:
import YData

# YData.download.download_class_code(12)   # get class code    
# YData.download.download_class_code(12, True)  # get the code with the answers 

YData.download.download_data("dow.csv")
YData.download_data("nba_salaries_2015_16.csv")
YData.download_data("daily_bike_totals.csv")
YData.download_data("gapminder_data.csv")

The file `dow.csv` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.
The file `nba_salaries_2015_16.csv` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.
The file `daily_bike_totals.csv` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.

In [10]:
## If you are using Google Colabs, you should install the YData packages and mount the your google drive by uncommenting and running the code below.

# !pip install https://github.com/yuejiechi/YData_package/tarball/master
# from google.colab import drive
# drive.mount('/content/drive')

In [11]:
import pandas as pd
import statistics
import numpy as np
from datetime import datetime
import seaborn as sns

import matplotlib.pyplot as plt
%matplotlib inline

## Practice problem 1

Using the `nba_salaries` data, create a data frame called `team_count` that displays the following columns:

1. `TEAM`: The team name of each NBA player represented.
2. `num_players`: The number of players on each team.

In [12]:
nba = pd.read_csv("nba_salaries_2015_16.csv")

## Practice problem 2

Suppose the data on the DOW Jones Industrial Average was loading in Python as a DataFrame in the name `dow`. Use Boolean masking to create a DataFrame that extracts data from all "Fridays". Save this to `dow_fridays`. Then, sort this new dataframe by `Open` values.

In [13]:
dow = pd.read_csv("dow.csv")
dow = dow.set_index("Date")

## Practice problem 3

Now visualize the distribution of the opening price of the DOW using seaborn.

## Practice problem 4

The code below loads data on the number of bike trips take each date on NYC citibikes, and also weather information. 

Use this data to create a scatter plot that shows the relationship between wind speed for a given date and the number of bike rides taken with both `matplotlib` and `seaborn`. Compare and contrast the two resulting plots and the process of making them. 

Also, calculate the correlation between wind speed and the number of bike trips taken on each date.

In [14]:
import statistics
bikes = pd.read_csv("daily_bike_totals.csv")
bikes.head(3)

,date,trips,precipitation,snow_depth,snowfall,max_temperature,min_temperature,average_wind_speed,dow,year,month,holiday,stations_in_service,weekday,weekday_non_holiday
0,2013-07-01,16650,0.838583,0.0,0.0,77.00,71.96,3.13171,1,2013,7,False,NaN,True,True
1,2013-07-02,22745,0.078740,0.0,0.0,82.04,71.96,2.68432,2,2013,7,False,NaN,True,True
2,2013-07-03,21864,0.531496,0.0,0.0,82.94,73.04,4.25018,3,2013,7,False,NaN,True,True

## Practice problem 5


Consider the following code, in which lines from Taylor Swift's "Love Story" are interspersed in William Shakespeare's Romeo and Juliet:


<pre>

lines =  ["Two households, both alike in dignity,",
          "On a balcony in summer air",
          "In fair Verona, where we lay our scene,",
          "See the lights, see the party, the ball gowns",
          "From ancient grudge break to new mutiny,",
          "See you make your way through the crowd",
          "Where civil blood makes civil hands unclean.",
          "And say, 'Hello'",
          "From forth the fatal loins of these two foes",
          "Little did I know",
          "A pair of star-cross'd lovers take their life;",
          "That you were Romeo, you were throwin' pebbles",
          "Whose misadventured piteous overthrows",
          "And my daddy said, 'Stay away from Juliet'",
          "Do with their death bury their parents' strife.",
          "And I was cryin' on the staircase",
          "The fearful passage of their death-mark'd love,",
          "Beggin' you, 'Please don't go,' and I said",
          "And the continuance of their parents' rage,",
          "'Romeo, take me somewhere we can be alone'",
          "Which, but their children's end, nought could remove,",
          "'I'll be waiting, all there's left to do is run'",
          "Is now the two hours' traffic of our stage;",
          "You'll be the prince and I'll be the princess",
          "The which if you with patient ears attend,",
          "It's a love story, baby, just say, 'Yes'",
          "What here shall miss, our toil shall strive to mend."]
                          
</pre>

If I wanted to print ONLY the text from Romeo and Juliet, I could code the following: `lines[_:_:_]`

Which numbers belong in the blanks above

a) 1, 14, 2

b) 0, 27, 2

c) 1, 27, 4

d) 0, 14, 4

In [15]:

lines =  ["Two households, both alike in dignity,",
          "On a balcony in summer air",
          "In fair Verona, where we lay our scene,",
          "See the lights, see the party, the ball gowns",
          "From ancient grudge break to new mutiny,",
          "See you make your way through the crowd",
          "Where civil blood makes civil hands unclean.",
          "And say, 'Hello'",
          "From forth the fatal loins of these two foes",
          "Little did I know",
          "A pair of star-cross'd lovers take their life;",
          "That you were Romeo, you were throwin' pebbles",
          "Whose misadventured piteous overthrows",
          "And my daddy said, 'Stay away from Juliet'",
          "Do with their death bury their parents' strife.",
          "And I was cryin' on the staircase",
          "The fearful passage of their death-mark'd love,",
          "Beggin' you, 'Please don't go,' and I said",
          "And the continuance of their parents' rage,",
          "'Romeo, take me somewhere we can be alone'",
          "Which, but their children's end, nought could remove,",
          "'I'll be waiting, all there's left to do is run'",
          "Is now the two hours' traffic of our stage;",
          "You'll be the prince and I'll be the princess",
          "The which if you with patient ears attend,",
          "It's a love story, baby, just say, 'Yes'",
          "What here shall miss, our toil shall strive to mend."]

## Practice problem 6

Let's say that you have a DataFrame called `USgdp` with the year in a column called `year`, and the United State's GDP per capita in a column called `gdpPercap`. 

Which one of these options would give you the total GDP change between the starting year and each later year? 

a. `np.diff(USgdp["gdpPercap"])`

b. `np.cumsum(USgdp["gdpPercap"])`

c. `np.diff(np.cumsum(USgdp["gdpPercap"]))`

d. `np.cumsum(np.diff(USgdp["gdpPercap"]))`

In [16]:
gapminder = pd.read_csv("gapminder_data.csv")
USgdp = gapminder[gapminder["country"] == "United States"][["year", "gdpPercap"]]
display(USgdp.head(3))

      year    gdpPercap
1608  1952  13990.48208
1609  1957  14847.12712
1610  1962  16173.14586