---
execute: 
  cache: false
format: 
  pdf:
    include-in-header: 
       text: |
         \newcommand{\textasciicaret}{\^{}}
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
    include-before-body:
        text: |
         \RecustomVerbatimEnvironment{verbatim}{Verbatim}{showspaces = false, showtabs = false, breaksymbolleft={}, breaklines}
---

# Homework 6: Pivot Tables and Mapping

Welcome to the sixth homework! In this homework you practice creating pivot tables and creating maps using geopandas. Please complete this notebook by filling in the cells provided. 

**Deadline:**

This assignment is due **Sunday March 08 at 11pm.** You can turn in the assignment up to 24 hours late for 90% credit (after that, the homework will only be accepted with a dean's excuse). 

Directly sharing answers is not okay, but discussing problems with the course staff or with other students is encouraged. Refer to the policies page to learn more about how to learn cooperatively.

You should start early so that you have time to get help if you're stuck. The drop-in office hours schedule can be found on Canvas.  You can also post questions or start discussions on Ed Discussion.

**NOTE ABOUT THE FIGURES IN THE PDF**: Note that the figures created from interactive plot (i.e., plotly) might not show up correctly when you print your homework to a pdf. This is fine/expected, and we will be grading these questions on the code you submit if the figures are not visable or are not showing up correctly. In general, interactive graphics are not meant to be printed and shared as pdfs.

## Getting started

In order to complete the homework, it is necessary to download a few files. Please run the code below **only once** to download data needed to complete the homework. To run the code, click in the cell below and press the play button (or press shift-enter).

In [1]:
# if you are running this notebook in colabs, please uncomment and run the following line
# !pip install https://github.com/emeyers/YData_package/tarball/master

In [2]:
# Please run this code once to download the files you will need to complete the homework 

import YData 

YData.download.download_data("college_scorecard_subset_2021_2022.csv")
YData.download.download_data("CCBASIC_categories.csv")
YData.download.download_data("connecticut.geojson")
YData.download.download_data("States_shapefile.geojson")

## 0. Quote and Reaction (5 points)

For this week's quote and reaction, please choose and read an article from [the pudding](https://pudding.cool/), which is a website that has interactive data analysis articles (often using javascript D3 library). Once you have read the article, please post a link to the article you choose below and briefly describe what the article was about and what you thought was interesting about it. 

Also, please [read this recent (and very short) article](https://yale.instructure.com/courses/115645/files/folder/readings?preview=12330099) from the New York Times about different map projects (you do not need to comment on this article below, although you can leave a short comment if you'd like).

The article I chose was:  (add a link here)

The article was about...

What I found interesting about the article was...

In [3]:
# This cell imports functions from packages we will use below.
# Please run it each time you load the Jupyter notebook

import numpy as np
import pandas as pd
import plotly
import plotly.express as px
import matplotlib.pyplot as plt

# plotly.offline.init_notebook_mode()

%matplotlib inline

## The College Scorecard data 

To practice creating interactive visualizations and mapping, we will use College Scorecard dataset. The dataset is created by the [United States](https://www.npr.org/sections/ed/2015/09/12/439742485/president-obamas-new-college-scorecard-is-a-torrent-of-data) government to allow consumers to compare the cost and value of higher education institutions in the United States. 

Full dataset can be found at https://collegescorecard.ed.gov/data/ and the full codebook can be download [here](https://collegescorecard.ed.gov/data/data-documentation). In order to make the data more manageable, I created a smaller dataset that contains only data from institutions which the predominant degree offered is a bachlor's degree, and that also only has a smaller subset of variables that are in the full dataset. A code book for the variables in this smaller dataset is below, and the next cell loads the data into pandas DataFrame.

#### Codebook

1. `UNITID`: Unit ID for institution

2. `INSTNM`: Institution name

3. `CITY`: School city

4. `STABBR`: State 

5. `ZIP` zip code

6. `HIGHDEG`: Higest degree offered. 3 is BA, 4 is graduate degree

7. `CONTROL`: Control of institution. 1 = public, 2 = private non-profit, 3 = private for profit

8. `LATITUDE`: Latitude

9. `LONGITUDE`: Longitude

10. `CCBASIC`: Carnegie Classification; e.g., 15 = Doctoral Universities: Very High Research Activity

11. `ADM_RATE`: Admission rate

12. `SAT_AVG`: Average SAT equivalent score of students admitted

13. `UGDS`: Enrollment of undergraduate certificate/degree-seeking students (student size)

14. `NPT4_PUB`: Average net price for Title IV institutions (public institutions)

15. `NPT4_PRIV`: Average net price for Title IV institutions (private for-profit and nonprofit institutions)

16. `TUITIONFEE_IN`: In-state tuition and fees cost

17. `TUITIONFEE_OUT`: Out-of-state tuition and fees cost

18. `TUITFTE`: Net tuition revenue per full-time equivalent student

19. `INEXPFTE`: Instructional expenditures per full-time equivalent student

20. `AVGFACSAL`: Average faculty salary

21. `PFTFAC`: Proportion of faculty that is full-time

22. `PCTPELL`: Percentage of undergraduates who receive a Pell Grant

23. `C100_4`: Completion rate for first-time, full-time students at four-year institutions (100% of expected time to completion). 100 percent of normal time is typically 4 years.

24. `C150_4`: Completion rate for first-time, full-time students at four-year institutions (150% of expected time to completion. 150 percent of normal time is typically 6 years. 

25. `GRAD_DEBT_MDN`: The median debt for students who have completed

26. `WDRAW_DEBT_MDN`: The median debt for students who have not completed

27. `PCIP27`: Percentage of degrees awarded in Mathematics And Statistics

28. `UGDS_MEN`: Total share of enrollment of undergraduate degree-seeking students who are men

29. `UGDS_WOMEN`: Total share of enrollment of undergraduate degree-seeking students who are women

30. `GRADS`: Number of graduate students

31. `BOOKSUPPLY`: Cost of attendance: estimated books and supplies cost

32. `ROOMBOARD_ON`: Cost of attendance: on-campus room and board cost

33. `ENDOWBEGIN`: Value of school's endowment at the beginning of the fiscal year

34. `ENDOWEND`: Value of school's endowment at the end of the fiscal year

35. `GT_THRESHOLD_P10`: Share of students earning more than a high school graduate (threshold earnings) 10 years after entry

36. `MD_EARN_WNE_MALE0_P10`: Median earnings of non-male students working and not enrolled 10 years after entry

37. `MD_EARN_WNE_MALE1_P10`: Median earnings of male students working and not enrolled 10 years after entry

In [4]:
scorecard = pd.read_csv("college_scorecard_subset_2021_2022.csv")

scorecard.head(3)

,UNITID,INSTNM,CITY,STABBR,ZIP,HIGHDEG,CONTROL,LATITUDE,LONGITUDE,CCBASIC,...,UGDS_MEN,UGDS_WOMEN,GRADS,BOOKSUPPLY,ROOMBOARD_ON,ENDOWBEGIN,ENDOWEND,GT_THRESHOLD_P10,MD_EARN_WNE_MALE0_P10,MD_EARN_WNE_MALE1_P10
0,100654,Alabama A & M University,Normal,AL,35762,4,1,34.783368,-86.568502,18.0,...,0.3978,0.6022,884.0,1600.0,9240.0,NaN,NaN,0.6044,36050.0,36377.0
1,100663,University of Alabama at Birmingham,Birmingham,AL,35294-0110,4,1,33.505697,-86.799345,15.0,...,0.3816,0.6184,8685.0,1200.0,12307.0,537349307.0,539858544.0,0.7472,42007.0,56164.0
2,100706,University of Alabama in Huntsville,Huntsville,AL,35899,4,1,34.724557,-86.640449,16.0,...,0.5891,0.4109,1972.0,2200.0,10652.0,77250279.0,75837207.0,0.7769,45170.0,66070.0

## 1. Pivot Tables

**Question 1.1 (3 points)**: To get a little more practice with pandas, in the cell below, please write code that prints the names of the 3 schools that have the highest endowments.

In [5]:
cc_categories = pd.read_csv("CCBASIC_categories.csv")
display(cc_categories.head(3))

   CCBASIC                            carnegie_classification
0       -2                                     Not applicable
1        0                                   (Not classified)
2        1  Associate's Colleges: High Transfer-High Tradi...

In [6]:
scorecard2 = scorecard.merge(cc_categories, on = 'CCBASIC')
scorecard2.head(3)

,UNITID,INSTNM,CITY,STABBR,ZIP,HIGHDEG,CONTROL,LATITUDE,LONGITUDE,CCBASIC,...,UGDS_WOMEN,GRADS,BOOKSUPPLY,ROOMBOARD_ON,ENDOWBEGIN,ENDOWEND,GT_THRESHOLD_P10,MD_EARN_WNE_MALE0_P10,MD_EARN_WNE_MALE1_P10,carnegie_classification
0,100654,Alabama A & M University,Normal,AL,35762,4,1,34.783368,-86.568502,18.0,...,0.6022,884.0,1600.0,9240.0,NaN,NaN,0.6044,36050.0,36377.0,Master's Colleges & Universities: Larger Programs
1,100663,University of Alabama at Birmingham,Birmingham,AL,35294-0110,4,1,33.505697,-86.799345,15.0,...,0.6184,8685.0,1200.0,12307.0,537349307.0,539858544.0,0.7472,42007.0,56164.0,Doctoral Universities: Very High Research Acti...
2,100706,University of Alabama in Huntsville,Huntsville,AL,35899,4,1,34.724557,-86.640449,16.0,...,0.4109,1972.0,2200.0,10652.0,77250279.0,75837207.0,0.7769,45170.0,66070.0,Doctoral Universities: High Research Activity

**Question 1.2 (4 points)**: 

Let's create a DataFrame called `scorecard_state_stats` where each row corresponds to a unique combination of state abbreviation and Carnegie Classification. The columns of the `scorecard_state_stats` should be: 

1. `STABBR`: The states abbreviation
2. `carnegie_classification`: The Carnegie Classification
3. `count`: The number of institutions in each state which a particular Carnegie Classification
4. `median_income`: The median of the `MD_EARN_WNE_MALE0_P10` variable (i.e., the median of the median incomes)

Once you have created `scorecard_state_stats` DataFrame, sort the values in it by the `count` variable and display the first 5 rows. 

Hint: You can group a DataFrame in pandas by multiple variables using `.groupby(['name_col1', 'name_col2'])`

**Question 1.3 (4 points)**: Let's visualize the scorecard data using heatmaps that shows the tuition revenue depends on the cc-type of college and on whether the college is a public college or non-profit private college. 

To start this analysis, use the `.pivot_table()` method to create a DataFrame called `scorecard_wide`. Each row of this DataFrame should correspond to one of the Carnegie Classification types. The table should also have the following properties:

1. The Index should be the Carnegie Classification 
2. There should be a column called `1` which has the median "Net tuition revenue per full-time equivalent student" for public schools (for each Carnegie Classification type). 
3. Likewise, there should a column called `2` which has the median "Net tuition revenue per full-time equivalent student" for private schools (for each Carnegie Classification type). 

Once you have created this basic `scorecard_wide` DataFrame, please modify it by doing the following:
1. Rename the `1` column to be `Public` and the `2` column to be `Private`.
2. Remove the column called `3`
3. Sort the values based on the values in the `Private` column
4. Drop any rows from the DataFrame that have missing values by using the `.dropna()` method. 

After you have created the `scorecard_wide` DataFrame, print the first of this DataFrame to show your work.

**Question 1.4 (4 points)**: As you know, since you need to turn in your final project as a pdf document, you won't be able to include interactive graphics on the project. Fortunately, you can still create non-interactive heatmaps of the data using seaborn. 

Let'e explore this now but creating the visualization above using the `sns.heatmap()` function where the arguments to the function should be the `scorecard_wide` DataFrame. Also set the `annot=True` to add written values on the heatmap, and `fmt=".0f"` so that the values are integers. Finally, set the x and y labels to empty strings to turn off these labels.

In [7]:
import seaborn as sns

## 2. Mapping

For the second part of this homework we will explore creating maps of data using the geopandas package. In particular, we will create maps where we add points at particular locations, and also choropleth maps where will fill in predefined regions based on particular values. Let's dive in!

**Question 2.1 (2 points)**: 

In order to create maps, we need to load data that has the boundary regions of the areas we would like to map. There are several different formats that are used to store such mapping data. We will load data that is in [GeoJson format](https://geojson.org/), which is a format that is more human-readible than other formats which can be useful if you want to look at the raw data. To start, we will load data on the state of Connecticut which was obtained from https://github.com/glynnbird/usstatesgeojson. 

The code below imports the geopandas packages and uses it to load our data on Connecticut into a geopandas DataFrame. As we discussed in class, a geopandas DataFrame is similar regular pandas DataFrame except that it has an extra column called "geometry" which contains geometric shapes (these shapes are defined as "Shapely objects" which [you are read more about here](https://shapely.readthedocs.io/en/stable/manual.html) if you are interested). For our Connecticut data, there is only one row which contains data on the state of Connecticut. As you can see, this geopandas DataFrame contains information on Connecticut (just like a regular pandas DataFrame has) along with the geometry column contains the outline of the state. 

To start, please use the geopandas `.plot()` method to plot the outline of the state. Also set the `color` argument to "orange" to make the fill color of the state orange, and the `edgecolor` argument to "green" to create a green outline around the state.

Also, for this **and all subsequent questions**, please be sure to use `ax.set_axis_off();` to turn remove the axes from the maps in order to make them look better.

In [8]:
import geopandas as gpd

ct_map = gpd.read_file('connecticut.geojson')

ct_map

,name,abbreviation,capital,city,population,area,waterarea,landarea,houseseats,statehood,group,geometry
0,Connecticut,CT,Hartford,Bridgeport,3596080,14356,1816,12541,5,1788-01-09,US States,"POLYGON ((-72.39743 42.0333, -72.19883 42.0309..."

In [9]:
# plot Connecticut here

**Question 2.2 (3 points)**: In order to have some interesting data to plot, let's convert our College Scorecard data into a geopandas DataFrame. Since geopandas DataFrames are just like regular pandas DataFrame with a geometry column, all we need to do is to load the regular College Scorecard data along with data specifying what should be in the geometry column. 

If you look at our `scorecard` DataFrame, you will notice that there are columns called `LATITUDE` and `LONGITUDE` which contain the latitude and longitude coordinate locations of each column. What we need to do is to convert these coordinates into "shapely" geometric POINT objects, which can be stored in our geometric column for our geopandas DataFrame. This can be done using the geopandas `gpd.points_from_xy(long, lat)` function, which takes array objects of longitude and latitude coordinates and returns a "GeometryArray" object that stores our points. 

Please use the `gpd.points_from_xy(long, lat)` function to create a name `college_geometries` which contains the locations of all colleges in our `scorecard` DataFrame. Also print out what type of object`college_geometries` is, and the first 10 values in `college_geometries` (hint, square brackets will help).

**Question 2.3 (3 points)**: 

Now that we have all the locations of colleges in the proper format, we can create a geopandas DataFrame using `gpd.GeoDataFrame()` function. This function takes a regular pandas DataFrame as a first argument, and we can set the values in the geometry column using the `geometry` argument. 

Please create a name `scorecard_gpd` that contains the scorecard data as a geopandas DataFrame. This DataFrame should contain all same columns as the original `scorecard` DataFrame, and should have the geometry column be the longitude and latitude coordinates of each college (as specified in the `college_geometries` name you created above). 

Once you have created this DataFrame, print the first 3 rows to show you have the correct answer.

**Question 2.4 (2 points)**: 

Now let's use the `scorecard_gpd` to create a new geopandas DataFrame called `ct_scorecard` that only has information on schools in Connecticut. Once you have created this DataFrame, print the first 3 rows to show your work.

Hint: Boolean masking or using the .query() method could be helpful here.

**Question 2.5 (3 points)**: 

Now we are ready to plot the locations of all schools in Connecticut. To do this, we can first plot a map of Connecticut, as we did question 2.1, but rather than displaying the plot, store the output of the plot in the name `base`. Also, for this plot of Connecticut, have the color be white and the outline be black.

Once you have created the `base` plot, you can then pass it to a second plot function that plots the locations of our colleges. To do this, call the `.plot()` method on our `ct_scorecard` DataFrame, with the following arguments:

1. Set the `ax` argument to our `base` object so that the outline of Connecticut is also shown. 
2. Set the `color` argument to "red" to make our points red
3. Set the markersize to 5 to make the points for each college an appropriate size.

Note: The plot you will create will look a bit off. You will fix this in the next question.

**Question 2.6 (3 points)**: As mentioned above, there is something off in the plot you created in question 2.5 - namely, you will notice an outlier where one college seems to be located way outside of Connecticut.

In the cell below, use pandas create a DataFrame called `outlier_school` which contains just data from this outlier school (and all the columns for the original `ct_scorecard` DataFrame). Then print out the DataFrame to see which school is the outlier.

**Question 2.7 (3 points)**: When faced with an outlier in a dataset, what we should do is to investigate why the point is an outlier. If you lookup the name of the school in google maps, you will notice that the coordinates of the school are different than what is in the `ct_scorecard` DataFrame. Thus it seems likely that for some reason, there was an error entering the coordinates for this school (which makes sense because all schools in Connecticut should be located inside the boarders of Connecticut!). 

Now that we have indentified that the outlier is due to an error, we should go ahead and fix this error. One way to do this would be to correct the mistaken coordinate either in the original data, or programmatically in Python. However, we are going to be lazy here and are going to just remove this school from our dataset. 

Please create a geopandas DataFrame called `ct_scorecard2` that has all the same data as `ct_scorecard` but that has the outlier school removed. Then recreate the plot you created in question 2.5 below. 

Hint: The `.drop(index_value)` method could be useful here, although there are several ways to remove the outlier row.

**Question 2.8 (3 points)**: Let's now switch gears and create a choropleth map of the mainland United States. The code below loads geometric information on the outlines of all states in the United States as a geopandas DataFrame called `usa`. 

In order to make our visualizations a little easier to see, let's just focus on the mainland United States, which are the "lower 48 states" that do not include Alaska and Hawaii. Please create a geopandas DataFrame called `usa_mainland` which only contains data from the "lower 48 states". Once you have created this DataFrame plot a map of these states.

Hint: the state abbreviation for Alaska is "AK" and the state abbreviation for Hawaii is "HI".

In [10]:
# choropleth map of USA

usa = gpd.read_file('States_shapefile.geojson')

usa = usa.drop(columns = ["FID", "Program", "Flowing_St", "FID_1"]) 

usa.head(3)

  State_Code State_Name                                           geometry
0         AL    ALABAMA  POLYGON ((-85.07007 31.9807, -85.11515 31.9074...
1         AK     ALASKA  MULTIPOLYGON (((-161.33379 58.73325, -161.3824...
2         AZ    ARIZONA  POLYGON ((-114.52063 33.02771, -114.55909 33.0...

In [11]:
# Create your usa_mainland geopandas DataFrame here and plot it

**Question 2.9 (4 points)**: Now that we have a map of the mainland USA, let's create a choropleth map where each state is filled with a color that represents that mean average SAT scores of colleges in the state. To do let's first create the data we need to plot. We can do this by first creating a DataFrame called `state_SAT` from the `scorecard` DataFrame which just has two columns that are:

1. `STABBR`: which is the abbreviation for each state.
2. `mean_SAT`: which is the mean average SAT scores of all colleges in each state.

Once you have created the `state_SAT` DataFrame, join it onto the `usa_mainland` DataFrame and save the results to the name `usa_endow_map`. Print the first 5 rows of this DataFrame to show you have the appropriate data. 

Hint: The `usa_endow_map` DataFrame should have 5 columns which are: `State_Code`, `State_Name`, `geometry`, `STABBR`, `mean_SAT`.

**Question 2.10 (4 points)**:  Now that we have the relevant data in the `usa_endow_map` let's create a choropleth map! In particular, each state is filled with a color based the mean of the average SAT scores of all colleges in a state.

To do this use the `.plot()` method with the following arguments: 

1. `column`: should be set to the name of the column that you want to fill in the color of each state based on its values.
2. `legend`: set this to `True` to see a legend
3. `legend_kwds`: Set this to the following dictionary `{'label': "CHANGE TO APPROPRIATE LABEL", 'orientation': "horizontal"}`

## 3. Class project!

As we discussed in class, your class project consists of a 6-10 page analysis (done in Jupyter) where you find a data set on your own, and apply the methods we have discussed in class to show some interesting insights. 

As a first step in this process, you need to select a data set! A list of a few sources where you can find data sets is on Canvas (on the left, under the link called "Data sources"). Please take some time this week to look through the data sets on this page and/or search for data you are interested in on Google or Bing. 

On the next homework, there will be a question where it asks you to list what your project will be on, and to also load a data set related to your project, so please start on this process now so that you are prepared.

## 4. Reflection (3 points)

Please reflect on how the homework went by going to Canvas, going to the Quizzes link, and clicking on reflection on homework 6.

## 5. Submission

Once you're finished filling in and running all cells, you should submit your assignment as a pdf on Gradescope. You can access Gradescope through Canvas on the left-side of the class home page. The problems in each homework assignment are numbered. When submitting on Gradescope, please **make sure to select the correct pages of your pdf that correspond to each problem**. Failure to mark pages correctly **will result in points being deducted** from your homework score.

To convert this Jupyter notebook document to a pdf please run the code in the cell below, which will create pdf document that you can upload to Gradescope. 

Please be sure to check that all the code and output are visible before submitting your pdf to Gradescope as **points will be deducted for missing code and output that is not visible** since we will not be able to grade this.

<font color='red'> **NOTE ABOUT THE FIGURES IN THE PDF**: As mentioned at the start of this homework, the figures created from interactive plot (i.e., plotly) might not show up correctly when you print your homework to a pdf. This is fine/expected, and we will be grading these questions on the code you submit if the figures are not visable or are not showing up correctly. In general, interactive graphics are not meant to be printed and shared as pdfs.

In [12]:
%%capture

!quarto render homework_06.ipynb --cache-refresh --to pdf

#### Alternative submission instructions

If converting your Jupyter notebook to a pdf using the command in the cell above does not work, an alternative way to convert your Jupyter notebook is:

1.  Go to "File" at the top-left of your Jupyter Notebook
2.  Under "Download as" (or "Save and Export Notebook As...") and select "HTML (.html)"
3.  After the .html has downloaded, open it and then select "File" and "Print" (note you will not actually be printing)
4.  From the print window, select the option to save as a .pdf


If you are running the assignment in a Google Colabs, you can use the following instructions: 
1.  Go to "File" at the top-left of your Jupyter Notebook and select "File" and "Print" (note you will not actually be printing)
2. From the print window, select the option to save as a .pdf
3. Be sure to look over the pdf file to make sure all your code and written work is saved in a clear way.